// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-2VeGNjyP7CJl6oXqACLye5aWq6VHHOU',
    appId: '1:966469874268:web:3b13deaad216983653ec99',
    messagingSenderId: '966469874268',
    projectId: 'nosql-assignment-873e4',
    authDomain: 'nosql-assignment-873e4.firebaseapp.com',
    storageBucket: 'nosql-assignment-873e4.firebasestorage.app',
    measurementId: 'G-9LXK2H794Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlx-yI5Jp0KZ8dZkgI5eZzXb21vkAFJY',
    appId: '1:966469874268:android:0c50e081cde777e253ec99',
    messagingSenderId: '966469874268',
    projectId: 'nosql-assignment-873e4',
    storageBucket: 'nosql-assignment-873e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8rzqgk1UiPIXCQH33kKTMYQT_P6OQFC4',
    appId: '1:966469874268:ios:f2a9a593aa349fb453ec99',
    messagingSenderId: '966469874268',
    projectId: 'nosql-assignment-873e4',
    storageBucket: 'nosql-assignment-873e4.firebasestorage.app',
    iosBundleId: 'com.example.kostLy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8rzqgk1UiPIXCQH33kKTMYQT_P6OQFC4',
    appId: '1:966469874268:ios:f2a9a593aa349fb453ec99',
    messagingSenderId: '966469874268',
    projectId: 'nosql-assignment-873e4',
    storageBucket: 'nosql-assignment-873e4.firebasestorage.app',
    iosBundleId: 'com.example.kostLy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCqr8NnuVApcyoJAo0Hlle5_yd_XIe2aM',
    appId: '1:966469874268:web:c5ad6221e4505ea353ec99',
    messagingSenderId: '966469874268',
    projectId: 'nosql-assignment-873e4',
    authDomain: 'nosql-assignment-873e4.firebaseapp.com',
    storageBucket: 'nosql-assignment-873e4.firebasestorage.app',
    measurementId: 'G-QGX3LJS82F',
  );
}
